# Workflow for building using CMake.
name: CMake Build
on:
  push:
    branches: [main]

jobs:

  tools:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          tools/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --release
      working-directory: tools
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-tools
        path: tools/target/release/tools.exe

  build:
    runs-on: windows-latest
    needs: tools
    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756
    # See: https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-actions-cache
    - name: Package Environment
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
    - name: Download Tools
      id: tools
      uses: actions/download-artifact@v4
      with:
        name: ${{ runner.os }}-tools
        path: artifacts
    - name: Python Dependencies # For glad
      run: python -m pip install jinja2
    - name: Configure
      run: >
        cmake
        -B build
        -S .
        --preset x64-release
        -DDATA_TOOL=${{ steps.tools.outputs.download-path }}/tools.exe
    - name: Build
      run: cmake --build build
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-demo
        path:
          build/*.exe
          build/*.dll
