# Workflow for building using CMake.
name: CMake Build
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: windows-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Tool Cache Restore
      uses: actions/cache/restore@v4
      id: restore-tools
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          tools/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Tool Build
      run: cargo build --release
      working-directory: tools

    - name: Tool Cache Save
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          tools/target/
        key: ${{ steps.restore-tools.outputs.cache-primary-key }}
