# Workflow for building using CMake.
name: CMake Build
on:
  push:
    branches: [main]

jobs:

  tools:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          tools/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --release
      working-directory: tools
    - name: Upload Archives
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-tools
        path: tools/target/release/tools.exe

  build:
    runs-on: windows-latest
    needs: tools
    steps:
    - uses: actions/checkout@v4
    - name: Install CMake and Ninja
      uses: lukka/get-cmake@341e8741adc519af67193f98e5f1c1e2b4c042ce
    - name: Run VCPkg
      uses: lukka/run-vcpkg@fdac52dc790413f4ad041fc50f576a0cf6df17c5
    - name: Download Tools
      id: tools
      uses: actions/download-artifact@v4
      with:
        name: ${{ runner.os }}-tools
        path: artifacts
    - name: Configure
      run: >
        cmake
        -B build
        -S .
        --preset x64-release
        -DDATA_TOOL=${{ steps.tools.artifacts.outputs.download-path }}
